source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SequenceOperation_Example', :exclusive => true do
  pod "SequenceOperation", :path => "../"
end

target 'SequenceOperation_Tests', :exclusive => true do
  pod "SequenceOperation", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
